version: "3"

volumes:
  mysql:
    driver: local
  wikijs:
    driver: local

services:
  mysql_wikijs:
    restart: always
    image: postgres
    container_name: postgredb
    networks:
      - internal
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikipasswd
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - /patch/to/data/wikijs/postgres:/var/lib/postgres
    labels:
      - "traefik.enable=false"

  wikijs:
    image: requarks/wiki:latest
    container_name: wikijs
    restart: always
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikipasswd
      DB_NAME: wiki
      PUID: UID
      PGID: GID
      TZ=Europe/Madrid
    volumes:
      - /patch/to/data/wikijs/wikijs:/config
      - /patch/to/data/wikijs/wikijs:/data
    labels:
      # wikijs
      - "traefik.enable=true"
      - "traefik.http.routers.wikijs.rule=Host(`YOUR_DOMAIN`)"
      - "traefik.http.routers.wikijs.entrypoints=websecure"
      - "traefik.http.routers.wikijs.tls=true"
      - "traefik.http.routers.wikijs.tls.certresolver=lets-encrypt"
      - "traefik.http.services.wikijs.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.wikijs.headers.sslredirect=true"
    networks:
      - proxy
      - internal

networks:
  proxy:
    external: true
  internal:
    external: false
